### ISSUE TITLE
Add additional category to whatWeDo.vue

### ISSUE THREAD

**Issue by wdower** [mitre/aura#32]
Need to refactor the homepage to be more friendly to readers who have no idea what any of the proper nouns we throw around are.

Current layout:

    <template>
        WHAT WE DO: validation, hardening, etc. etc.
        ________________________________
        HOW WE DO IT: <huge mess of similarly-named Heimdall and InSpec links>
    </template>

If I am an agency head who is just now hearing about "OpsSecDev" or whatever, I don't know what InSpec and Heimdall are or how they relate.

What I suggest the layout should be:

    <template>
        WHAT WE DO: validation, hardening, etc. etc.
        __________________________
        HOW WE DO IT: <basic overview of InSpec and Heimdall - just enough to define the terms in broad strokes>
        __________________________
        TOOLS WE [ USE | DEVELOP ]: <the content currently under WHAT WE DO, like InSpecJS Tools and Heimdall Server>
    </template>

**Comment by wdower** [comment]
New plan after discussing with Aaron.
    
    <template>
        WHAT WE DO: validation, hardening, etc. etc.
        __________________________
        HOW WE DO IT: <basic overview of process chain for secure development - there are INPUTS (Inspec etc.), which are tools for creating security data, TRANSFORMATIONS (*JS_tools, etc.) which package the security data into usable formats, and OUTPUTS (pick your favorite flavor of Heimdall) which allow for actually analyzing oodles of security data>
        __________________________
        TOOLS WE BUILT: <more detail on stuff like heimdall server vs. heimdall lite>
    </template>

**Comment by aaronlippold** [comment]
Fixed by #43
